sed 's/^titre:.*$/titre: Programme de colles semaine 01/g' semaine01.html > semaine01.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 02/g' semaine02.html > semaine02.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 03/g' semaine03.html > semaine03.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 04/g' semaine04.html > semaine04.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 07/g' semaine07.html > semaine07.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 08/g' semaine08.html > semaine08.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 09/g' semaine09.html > semaine09.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 11/g' semaine11.html > semaine11.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 12/g' semaine12.html > semaine12.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 13/g' semaine13.html > semaine13.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 14/g' semaine14.html > semaine14.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 15/g' semaine15.html > semaine15.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 16/g' semaine16.html > semaine16.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 17/g' semaine17.html > semaine17.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 18/g' semaine18.html > semaine18.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 19/g' semaine19.html > semaine19.html.edit
sed 's/^titre:.*$/titre: Programme de colles semaine 05-06/g' semaine05-06.html > semaine05-06.html.edit
